"""add user_id to analyses

Revision ID: 40c10dfcadb4
Revises: a8818d959d74
Create Date: 2026-05-27 17:24:04.840628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c10dfcadb4'
down_revision: Union[str, Sequence[str], None] = 'a8818d959d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'analyses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.drop_column('analyses', 'user_id')
    # ### end Alembic commands ###
